version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - misspell
  exclusions:
    paths:
      - internal/api

settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
